#!/usr/bin/env bash
# RevenueCat 5.55.3 doesn't compile under Swift 6.4 (Xcode 27).
#
# PaywallColor declares a public struct whose only public stored property is
# `stringRepresentation`, with a fileprivate `_underlyingColor` alongside it.
# Swift 6.4 synthesizes a *public* memberwise initializer for such a struct,
# but only over the public properties — so it becomes `init(stringRepresentation:)`,
# which collides with the public throwing initializer declared in the extension:
#
#   error: invalid redeclaration of synthesized memberwise 'init(stringRepresentation:)'
#
# Fix: move the existing private designated initializer into the struct body.
# A user-declared initializer in the type's main declaration suppresses memberwise
# synthesis, so the collision goes away and the designated init still serves the
# `init(stringRepresentation:underlyingColor:)` call chain.
#
# The file lives in ios/Pods/, which is gitignored and regenerated by pod install,
# so this script must be re-run after each `pod install` / prebuild.
#
# Idempotent: does nothing if already patched. Exits 0 (with a notice) if the
# pod isn't installed or if upstream has changed in a way the patch can't apply —
# check the notice, the patch may no longer be needed after a RevenueCat bump.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET="$APP_DIR/ios/Pods/RevenueCat/Sources/Paywalls/PaywallColor.swift"

if [[ ! -f "$TARGET" ]]; then
  echo "patch-revenuecat-swift64: RevenueCat pod not installed, skipping"
  exit 0
fi

python3 - "$TARGET" << 'PYEOF'
import sys

path = sys.argv[1]
src = open(path).read()

if 'Declared in the struct body (not an extension)' in src:
    print("patch-revenuecat-swift64: already patched, skipping")
    sys.exit(0)

designated = """    /// "Designated" initializer
    private init(stringRepresentation: String, underlyingColor: (any Sendable)?) {
        self.stringRepresentation = stringRepresentation
        self._underlyingColor = underlyingColor
    }
"""
anchor = "    // Only available from iOS 13\n    fileprivate var _underlyingColor: (any Sendable)?\n"

if designated not in src or anchor not in src:
    print("patch-revenuecat-swift64: unexpected RevenueCat source layout — patch NOT applied.")
    print("  Upstream likely changed; re-check whether this patch is still needed.")
    sys.exit(0)

moved = anchor + """
    /// "Designated" initializer.
    /// Declared in the struct body (not an extension) so it suppresses the
    /// synthesized memberwise initializer: since Swift 6.4 that memberwise init
    /// is `init(stringRepresentation:)`, which clashes with the public throwing
    /// initializer below.
    private init(stringRepresentation: String, underlyingColor: (any Sendable)?) {
        self.stringRepresentation = stringRepresentation
        self._underlyingColor = underlyingColor
    }
"""

src = src.replace(designated, "", 1).replace(anchor, moved, 1)
open(path, 'w').write(src)
print("patch-revenuecat-swift64: applied")
PYEOF
